# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default  
  demands:
    - Agent.OS -equals Windows_NT  

variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndTest
  displayName: 'Compilar y probar en agente Windows'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'  # Ajusta según tu versión de .NET

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Compilar proyecto'

  - script: dotnet test --no-build --verbosity normal
    displayName: 'Ejecutar pruebas unitarias'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'


